exclude: "^docs/|.idea|devcontainer.json|tests/fixtures|__snapshots__/.*\\.ambr|manifest.json"
default_stages: [pre-commit]

default_language_version:
  python: python3.14

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
        exclude: (\.vscode)
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: detect-private-key

  - repo: https://github.com/fsfe/reuse-tool
    rev: a1bb792acda6fd0724936b4ebbdbc8eceb9c0459 # v6.2.0
    hooks:
      - id: reuse

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 423ab5081e037d3c692113d654d49ea9e3ee0066 # v1.32.0
    hooks:
      - id: django-upgrade
        args: ["--target-version", "6.1"]

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: 76675b68608b5643655650bf461b7d2abb2e2a52 # v1.44.2
    hooks:
      - id: djlint-django

  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: b8bfd27da9514450edbc0fe5254bc3ba3d3032c6 # 1.9.0
    hooks:
      - id: djade
        args: [--target-version, "5.2"]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95 # v0.11.0.1
    hooks:
      - id: shellcheck
        exclude: ".envrc"
        args: [-e, SC1091]

  - repo: https://github.com/crate-ci/typos
    rev: a8168dc2984a9e2352f183ffe788f0f23a300389 # v1.49.1
    hooks:
      - id: typos

  - repo: local
    hooks:
      - id: stylelint
        name: stylelint
        entry: npx stylelint
        args: [--fix]
        language: system
        types: [css]

      - id: eslint
        name: eslint
        entry: npx eslint
        args: [--fix]
        language: system
        types: [javascript]

      - id: prettier
        name: prettier
        entry: npx prettier
        args: [--write]
        language: system
        types_or: [yaml, css, javascript, json]
        exclude: (\.vscode)

      - id: import-linter
        name: import-linter
        entry: env
        args:
          - uv
          - run
          - lint-imports
        language: system
        pass_filenames: false

      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix --force-exclude
        types_or: [python, pyi, jupyter]
        require_serial: true
        language: system

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude
        types_or: [python, pyi, jupyter]
        require_serial: true
        language: system

      - id: mypy
        name: mypy
        entry: env
        args:
          - DATABASE_URL=sqlite:///mypy.db
          - IS_PRODUCTION=True
          - DJANGO_SECRET_KEY=test-key
          - DJANGO_ADMIN_URL=admin/
          - uv
          - run
          - mypy
          - legadilo
          - config
        language: system
        types: [python]
        pass_filenames: false

      - id: django-check
        name: django-check
        entry: env
        args:
          - DATABASE_URL=sqlite:///mypy.db
          - IS_PRODUCTION=True
          - DJANGO_SECRET_KEY=test-key
          - DJANGO_ADMIN_URL=admin/
          - uv
          - run
          - python
          - manage.py
          - check
          - --fail-level=WARNING
        language: system
        types: [python]
        pass_filenames: false

      - id: check-po
        name: check-po
        entry: env
        args:
          - uv
          - run
          - python
          - manage.py
          - makemessages
          - --all
          - --no-location
        language: system
        pass_filenames: false

      - id: type-check-browser-extension
        name: type-check-browser-extension
        entry: npm --prefix browser-extension run typecheck
        language: system
        pass_filenames: false
        types: [javascript]
        files: "^browser-extension/.*\\.js$"

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
