[project]
name = "legadilo"
description = "Legadilo is a project to help you subscribe to RSS feeds, save articles and organize them easily with tags and full customizable reading lists!"
readme = "README.md"
license = "AGPL-3.0-or-later"
license-files = ["LICENSE"]
version = "26.07.1"
requires-python = ">=3.14"
dependencies = [
    # General
    "argon2-cffi >= 23.1.0", # https://github.com/hynek/argon2_cffi
    "whitenoise[brotli] >= 6.8.2", # https://github.com/evansd/whitenoise
    "psycopg[binary,pool] >= 3.2.3", # https://github.com/psycopg/psycopg
    "rich >= 13.9.4", # https://rich.readthedocs.io/en/stable/
    # Django
    "django >= 5.1.3", # https://www.djangoproject.com/
    "django-environ >= 0.11.2", # https://github.com/joke2k/django-environ
    "django-allauth[mfa] >= 65.2.0", # https://github.com/pennersr/django-allauth
    "django-crispy-forms >= 2.3", # https://github.com/django-crispy-forms/django-crispy-forms
    "crispy-bootstrap5 >= 2024.10", # https://github.com/django-crispy-forms/crispy-bootstrap5
    "django-version-checks >= 1.13.0", # https://github.com/adamchainz/django-version-checks
    "django-extra-checks >= 0.15.1", # https://github.com/kalekseev/django-extra-checks
    "django-axes >= 7.0.0", # https://github.com/jazzband/django-axes
    "django-htmx >= 1.21.0", # https://django-htmx.readthedocs.io/en/latest/
    "django-ninja >= 1.3.0", # https://django-ninja.dev
    "django-cors-headers >= 4.6.0", # https://github.com/adamchainz/django-cors-headers#readme
    # Project
    #feedparser = "^6.0.11"  # https://feedparser.readthedocs.io/en/latest/
    # We must use git because the released version has a bug around media parsing.
    # See https://github.com/kurtmckee/feedparser/pull/441
    "feedparser",
    "python-slugify >= 8.0.4", # https://github.com/un33k/python-slugify
    "httpx2 >= 2.12.0", # https://httpx2.pydantic.dev/
    "beautifulsoup4 >= 4.12.3", # https://www.crummy.com/software/BeautifulSoup/bs4/doc/
    "nh3 >= 0.2.17", # https://nh3.readthedocs.io/en/latest/
    "python-dateutil >= 2.9.0.post0", # https://github.com/dateutil/dateutil
    "defusedxml >= 0.7.1", # https://github.com/tiran/defusedxml
    "markdown-it-py[linkify] >= 4.0.0", # https://markdown-it-py.readthedocs.io/en/latest/index.html
    "pydantic >= 2.10.2", # https://docs.pydantic.dev/latest/
    "pyjwt >= 2.10.1", # https://pyjwt.readthedocs.io/en/stable/
]

[dependency-groups]
dev = [
    # Testing
    "pytest >= 8.3.3", # https://github.com/pytest-dev/pytest
    "pytest-sugar >= 1.0.0", # https://github.com/Frozenball/pytest-sugar
    "httpx2-pytest >= 1.0.1", # https://github.com/angryfoxx/httpx2-pytest
    "pytest-mock >= 3.14.0", # https://pytest-mock.readthedocs.io/en/latest/
    "pytest-socket >= 0.7.0", # https://github.com/miketheman/pytest-socket
    "pytest-env >= 1.1.5", # https://github.com/pytest-dev/pytest-env
    "pytest-cov >= 6.0.0", # https://github.com/pytest-dev/pytest-cov
    "time-machine >= 2.16.0", #  https://github.com/adamchainz/time-machine
    # Code quality
    "pre-commit >= 4.0.1", # https://github.com/pre-commit/pre-commit
    "import-linter >= 2.9", # https://github.com/seddonym/import-linter/tree/main
    "ruff>=0.12.0",
    "reuse>=5.0.2", # To enforce license conformity: https://reuse.software/
    # Django
    "factory-boy >= 3.3.1", # https://github.com/FactoryBoy/factory_boy
    "django-debug-toolbar >= 4.4.6", # https://github.com/jazzband/django-debug-toolbar
    "pytest-django >= 4.9.0", # https://github.com/pytest-dev/pytest-django
    "django-browser-reload >= 1.17.0", # https://pypi.org/project/django-browser-reload/
    "django-watchfiles >= 1.0.0", # https://github.com/adamchainz/django-watchfiles
    "django-extensions >= 3.2.3", # https://github.com/django-extensions/django-extensions
    # Typing
    "types-python-dateutil >= 2.9.0.20240906",
    "mypy >= 1.13.0", # https://github.com/python/mypy
    "django-stubs[compatible-mypy] >= 5.1.1", # https://github.com/typeddjango/django-stubs
    "types-beautifulsoup4 >= 4.12",
    "syrupy>=6.0.0", # https://github.com/syrupy-project/syrupy
]
prod = [
    "gunicorn>=23.0.0",
    "sentry-sdk[django] >= 2.18.0",
]
doc = [
    "sphinx >= 8.1.3", # https://github.com/sphinx-doc/sphinx
    "sphinx-autobuild >= 2024.10.3", # https://github.com/GaretJax/sphinx-autobuild
    "myst-parser >= 4.0.0", # https://myst-parser.readthedocs.io/en/stable/intro.html
]

[tool.uv]
default-groups = ["dev"]
exclude-newer = "7 days"

[tool.uv.sources]
feedparser = { git = "https://github.com/Jenselme/feedparser.git", rev = "jen-release" }


# ==== pytest ====
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ds=config.settings --reuse-db --disable-socket --allow-unix-socket --allow-hosts=localhost"
python_files = [
    "tests.py",
    "test_*.py",
]
filterwarnings = [
    # We know and aren’t impacted.
    "ignore:To avoid breaking existing software while fixing issue 310",
]
env = [
    "LOGGING_RICH_TRACEBACK=False", # This slows downs test and we don’t need it.
    "ENABLE_DEBUG_TOOLBAR=False", # This messes up the test suite.
]
env_files = [
    "devops/envs/local/django"
]

# ==== Coverage ====
[tool.coverage.run]
include = ["legadilo/**"]
omit = ["*/migrations/*", "*/tests/*"]
plugins = []


# ==== Ruf ====
[tool.ruff]
line-length = 100
target-version = "py314"
exclude = [
    "docs/**",
]

[tool.ruff.lint]
preview = true
select = [
    "F", "E", "W", "C", "I", "N", "UP", "ASYNC", "S", "BLE", "FBT", "B", "A", "COM", "DTZ", "T",
    "DJ", "ICN", "RSE", "PT", "ISC", "RET", "SIM", "INT", "PTH", "ERA", "PGH", "PL", "FLY",
    "FURB", "LOG", "G", "RUF", "D", "UP"
]
ignore = [
    "RUF012", # RUF012 Mutable class attributes should be annotated with `typing.ClassVar`
    "RUF067", # Non empty init module
    "COM812", # missing-trailing-comma (the formatter will do this)
    "ISC001", # single-line-implicit-string-concatenation (the formatter will do this)
    "PLR6301", # Method XXX could be a function, class method, or static method
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D103", # Missing docstring in public function
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in magic method
    "D106", # Missing docstring in public nested class
    "D107", # Missing docstring in __init__
    "D415", # First line should end with a period, question mark, or exclamation point
]

[tool.ruff.lint.per-file-ignores]
"legadilo/**/tests/**/test_*.py" = [
    # at least this three should be fine in tests:
    "S101", # asserts allowed in tests...
    "ARG", # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    "PLR0904", # Too many public methods.
    "PLR2004", # Magic value used in comparison, ...
    "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
    "S106", # Possible hardcoded password
]
"legadilo/feeds/tests/test_utils/test_article_fetching.py" = [
    "E501",
    "RUF001", # String contains ambiguous `’`
]
"legadilo/**/factories.py" = [
    "FBT001", # Boolean-typed positional argument in function definition
    "ARG002", #  Unused method argument
    "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar`
]
"legadilo/**/migrations/*.py" = [
    "E501", # Line too long.
    "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar`
]
"config/wsgi.py" = [
    "ERA001", # Found commented-out code
]
"config/asgi.py" = [
    "ERA001", # Found commented-out code
]
"config/settings.py" = [
    "ERA001", # Found commented-out code
]

[tool.ruff.format]
preview = true
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint.isort]
known-first-party = [
    "legadilo",
    "config",
]

[tool.ruff.lint.pylint]
max-args = 6
allow-dunder-method-names = ["__get_pydantic_core_schema__"]

[tool.ruff.lint.pydocstyle]
convention = "google"


# ==== curlylint ====
[tool.curlylint.rules]
# All role attributes must be valid.
# See https://www.curlylint.org/docs/rules/aria_role.
aria_role = true
# Forms cannot be rendered with as_table, as_ul, or as_p
# See https://www.curlylint.org/docs/rules/django_forms_rendering.
django_forms_rendering = true
# The `lang` attribute must be present.
# See https://www.curlylint.org/docs/rules/html_has_lang.
html_has_lang = true
# The `alt` attribute must be present.
# See https://www.curlylint.org/docs/rules/image_alt.
image_alt = true
# Use tabs.
# See https://www.curlylint.org/docs/rules/indent.
indent = 4
# `user-scalable=no` must not be used, and `maximum-scale` should be 2 or above.
# See https://www.curlylint.org/docs/rules/meta_viewport.
meta_viewport = true
# The `autofocus` attribute must not be used.
# See https://www.curlylint.org/docs/rules/no_autofocus.
no_autofocus = true
# Avoid positive `tabindex` values, change the order of elements on the page instead.
# See https://www.curlylint.org/docs/rules/tabindex_no_positive.
tabindex_no_positive = true


# ==== mypy ====
[tool.mypy]
python_version = "3.14"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
plugins = [
    "mypy_django_plugin.main",
]
exclude = [
    # mypy gets messed up when factories are used instead of models instances.
    "test.*\\.py$"
]

[[tool.mypy.overrides]]
# Django migrations should not produce any errors:
module = "*.migrations.*"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "config.settings"


# ==== djLint ====
[tool.djlint]
blank_line_after_tag = "load,extends"
close_void_tags = true
format_css = true
format_js = true
# TODO: remove T002 when fixed https://github.com/Riverside-Healthcare/djLint/issues/687
ignore = "H006,H025,H030,H031,T002"
include = "H017,H035"
indent = 4
max_line_length = 119
profile = "django"
custom_blocks = "partialdef"

[tool.djlint.css]
indent_size = 4

[tool.djlint.js]
indent_size = 4


[tool.importlinter]
root_package = "legadilo"

[[tool.importlinter.contracts]]
name = "Enforce Django apps layering"
type = "layers"
layers = [
    "legadilo.import_export",
    "legadilo.feeds",
    "legadilo.reading",
    "legadilo.users",
    "legadilo.core",
]
ignore_imports = [
    "legadilo.reading.tests.test_models.test_article -> legadilo.feeds.tests.factories",
    "legadilo.users.tests.models.test_user -> legadilo.feeds.tests.factories",
    "legadilo.reading.tests.test_views.test_delete_article_view -> legadilo.feeds.tests.factories",
    "legadilo.reading.tests.test_views.test_delete_article_view -> legadilo.feeds.models",
    "legadilo.reading.tests.test_views.test_search_views -> legadilo.feeds.models",
    "legadilo.reading.tests.test_views.test_search_views -> legadilo.feeds.tests.factories",
    "legadilo.users.tests.views.test_user_views -> legadilo.feeds.tests.factories",
    "legadilo.users.tests.views.test_user_views -> legadilo.reading.tests.factories",
    "legadilo.users.tests.views.test_stats_views -> legadilo.feeds.tests.factories",
    "legadilo.users.tests.views.test_stats_views -> legadilo.reading.tests.factories",
    "legadilo.users.tests.models.test_user -> legadilo.reading.tests.factories",
    "legadilo.core.management.commands.setup_test_db -> legadilo.users.models",
    "legadilo.core.management.commands.setup_test_db -> legadilo.feeds.constants",
    "legadilo.core.management.commands.setup_test_db -> legadilo.feeds.models",
    "legadilo.core.management.commands.setup_test_db -> legadilo.feeds.services.feed_parsing",
    "legadilo.core.management.commands.setup_test_db -> legadilo.reading.models",
    "legadilo.core.management.commands.setup_test_db -> legadilo.reading.services.article_fetching",
]
