version = 1

# Documentation
[[annotations]]
path = [
    "docs/**/*.md",
    "docs/**/*.rst",
]
SPDX-FileCopyrightText = "Legadilo contributors"
SPDX-License-Identifier = "CC-BY-SA-4.0"

# Migrations
[[annotations]]
path = [
    "legadilo/**/migrations/*.py",
]
SPDX-FileCopyrightText = "Legadilo contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

# Templates
[[annotations]]
path = [
    "legadilo/templates/**/*.html",
    "legadilo/templates/**/*.txt",
]
SPDX-FileCopyrightText = "Legadilo contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

# Snapshot files
[[annotations]]
path = [
    "legadilo/*/tests/**/__snapshots__/**/*.ambr",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# Migrations
[[annotations]]
path = [
    "legadilo/*/migrations/*.py"
]
SPDX-FileCopyrightText = "Legadilo contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

# Test fixtures
[[annotations]]
path = [
    "legadilo/*/tests/**/*.xml",
    "legadilo/*/tests/**/*.csv",
    "legadilo/*/tests/**/*.json",
    "legadilo/*/tests/**/*.opml",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# Computer-generated files.
[[annotations]]
path = [
    "legadilo/templates/website/security.txt",
    "uv.lock",
    "package-lock.json",
    "browser-extension/package-lock.json",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# IDE settings
[[annotations]]
path = [
    ".idea/**/*",
    ".vscode/*",
    ".devcontainer/*",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# Browser extension translations
[[annotations]]
path = [
    "browser-extension/src/_locales/**/*.json"
]
SPDX-FileCopyrightText = "Legadilo contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

# Various technical files.
[[annotations]]
path = [
    ".envrc",
    ".vscode/*",
    ".dockerignore",
    ".editorconfig",
    ".envrc",
    ".gitattributes",
    ".github/dependabot.yml",
    ".github/workflows/ci.yml",
    ".gitignore",
    ".pre-commit-config.yaml",
    ".prettierrc.json",
    ".stylelintrc.json",
    ".nvmrc",
    ".npmrc",
    "_typos.toml",
    "eslint.config.cjs",
    "package.json",
    "pyproject.toml",
    "browser-extension/package.json",
    "browser-extension/tsconfig.json",
    "browser-extension/src/manifest.json",
    "browser-extension/src/vendor/.gitignore",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
