# Generated by Django 6.1.1 on 2026-09-22 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading", "0005_fill_missing_slugs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="readinglist",
            name="show_unread_count",
            field=models.CharField(
                choices=[("COUNT", "Count"), ("INDICATOR", "Indicator"), ("NOTHING", "Nothing")],
                default="COUNT",
                help_text="How to show the count of unread articles in the reading list: either the count, an indicator or nothing.",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinglist",
            constraint=models.CheckConstraint(
                condition=models.Q(("show_unread_count__in", ["COUNT", "INDICATOR", "NOTHING"])),
                name="reading_readinglist_show_unread_count_valid",
            ),
        ),
    ]
