# Generated by Django 6.1.1 on 2026-09-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="article_details_font_family",
            field=models.CharField(
                choices=[
                    ("system-ui", "System UI"),
                    ("serif", "Browser Serif"),
                    ("sans-serif", "Browser Sans Serif"),
                ],
                default="system-ui",
                help_text="'System UI' is the font used by your desktop environment, 'browser serif' and 'browser sans-serif' are the default fonts defined in your browser settings.",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="article_details_font_size_desktop",
            field=models.CharField(
                choices=[
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                    ("larger", "Larger"),
                ],
                default="medium",
                help_text="Font size in pixels for desktop devices (>= 992px wide).",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="article_details_font_size_mobile",
            field=models.CharField(
                choices=[
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                    ("larger", "Larger"),
                ],
                default="medium",
                help_text="Font size in pixels for mobile devices (< 768px wide).",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="article_details_font_size_tablet",
            field=models.CharField(
                choices=[
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                    ("larger", "Larger"),
                ],
                default="medium",
                help_text="Font size in pixels for tablet devices (>= 768px wide and < 992px wide).",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="article_details_max_width_desktop",
            field=models.CharField(
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                default="medium",
                help_text="Maximum width of article details for desktop devices (>= 992px wide).",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="article_details_max_width_tablet",
            field=models.CharField(
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                default="medium",
                help_text="Maximum width of article details for tablet devices (>= 768px wide and < 992px wide).",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "article_details_font_family__in",
                    ["system-ui", "serif", "sans-serif"],
                )),
                name="users_usersettings_article_details_font_family_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "article_details_font_size_desktop__in",
                    ["small", "medium", "large", "larger"],
                )),
                name="users_usersettings_article_details_font_size_desktop_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "article_details_font_size_mobile__in",
                    ["small", "medium", "large", "larger"],
                )),
                name="users_usersettings_article_details_font_size_mobile_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "article_details_font_size_tablet__in",
                    ["small", "medium", "large", "larger"],
                )),
                name="users_usersettings_article_details_font_size_tablet_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "article_details_max_width_desktop__in",
                    ["small", "medium", "large"],
                )),
                name="users_usersettings_article_details_max_width_desktop_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersettings",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "article_details_max_width_tablet__in",
                    ["small", "medium", "large"],
                )),
                name="users_usersettings_article_details_max_width_tablet_valid",
            ),
        ),
    ]
